# Generated by Django 3.2 on 2022-07-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletteruser',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
